# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rational_steck <- function(l, h) {
    .Call(`_highPrecisionSteck_rational_steck`, l, h)
}

rational_row <- function(l, h) {
    .Call(`_highPrecisionSteck_rational_row`, l, h)
}

high_steck <- function(l, h, prec, upperBound) {
    .Call(`_highPrecisionSteck_high_steck`, l, h, prec, upperBound)
}

high_row <- function(l, h, prec, upperBound) {
    .Call(`_highPrecisionSteck_high_row`, l, h, prec, upperBound)
}

set_max_binomial <- function(n) {
    invisible(.Call(`_highPrecisionSteck_set_max_binomial`, n))
}

get_log_prod <- function() {
    .Call(`_highPrecisionSteck_get_log_prod`)
}

C_log_prod <- function(n) {
    .Call(`_highPrecisionSteck_C_log_prod`, n)
}

C_log_beta <- function(a, b) {
    .Call(`_highPrecisionSteck_C_log_beta`, a, b)
}

C_lchoose <- function(n, k) {
    .Call(`_highPrecisionSteck_C_lchoose`, n, k)
}

